name: Autograding Tests
'on':
  - push
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  list-files:
   runs-on: ubuntu-latest
   outputs:
    paths: ${{ steps.list-files.outputs.paths }}
   steps:
     - name: List Files
       id: list-files
       uses: mirko-felice/list-files-action@v3.0.5
       with:
        repo: ${{ github.repository }}
        ref: ${{ github.ref }}
        path: "tests/testthat"
        ext: ".R"

  run-autograding-tests:
    needs: list-files  
    runs-on: ubuntu-latest
    container: docker://ghcr.io/lin611-2024/devcontainer/bayesdevcontainer:4
    if: github.actor != 'github-classroom[bot]'
    strategy:
      matrix:
        paths: ${{ fromJson(needs.list-files.outputs.paths) }}    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: runtest
      id: runtest
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: runtest
        command: Rscript ${{ matrix.paths }}
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        RUNTEST_RESULTS: "${{steps.runtest.outputs.result}}"
      with:
        runners: runtest
